### ISSUE TITLE
Possibility to add CookieDeclaration to a page

### ISSUE THREAD

**Issue by giraffewoods** [MEOM/meom-3rd-party-scripts#2]
The CookieDeclaration script looks like this:

`<script id="CookieDeclaration" src="https://consent.cookiebot.com/xxxx/cd.js" type="text/javascript" async></script>`

It would be nice to have a shortcode or something so we don't have to add the script to the editor.
@SinttiSalminen you had some insight how to add the language version to the script?

**Comment by SinttiSalminen** [comment]
Language version needs a language code as data-culture to the script, like this: 
<script id="CookieDeclaration" data-culture="FI" src="https://consent.cookiebot.com/35d2e4ca-17db-48fb-80c5-917474b1b1af/cd.js" type="text/javascript" async=""></script>

Could it be fetched from Polylang's current language and passed to the script automatically? That data-culture isn't needed if the site is single language though.
